### ISSUE TITLE
Master fails with "Error: 1050 Table 'sunittest_smw_object_ids' already exists ()"

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticGlossary#29]
### Setup and configuration

- MW version: master
- PHP version:
- DB (MySQL etc.):
- SMW version:
- SG version:
- Lingo version:

### Issue

https://travis-ci.org/SemanticMediaWiki/SemanticGlossary/jobs/246499446

```
Using PHP 5.5.21

Semantic Glossary:  2.2.0

Semantic MediaWiki: 3.0.0-alpha (fa6e492, SMWSQLStore3, mysql)
MediaWiki:          1.30.0-alpha (, MediaWiki vendor autoloader)
Site language:      en

Execution time:     2017-06-24 09:10
Debug logs:         Disabled
Xdebug:             2.2.7 (enabled)

PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

Runtime:	PHP 5.5.21 with Xdebug 2.2.7
Configuration:	/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticGlossary/phpunit.xml.dist

..........................[dc633e9c62e64ea077cf6073] [no req]   Wikimedia\Rdbms\DBQueryError from line 1145 of /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: CREATE TABLE `its_a_mw`.`sunittest_smw_object_ids` (smw_id INT(8) UNSIGNED NOT NULL KEY AUTO_INCREMENT,smw_namespace INT(11) NOT NULL,smw_title VARBINARY(255) NOT NULL,smw_iw VARBINARY(32) NOT NULL,smw_subobject VARBINARY(255) NOT NULL,smw_sortkey VARBINARY(255) NOT NULL,smw_sort VARBINARY(255),smw_proptable_hash MEDIUMBLOB) ENGINE=InnoDB, DEFAULT CHARSET=binary
Function: SMW\SQLStore\TableBuilder\MySQLTableBuilder::doCreateTable
Error: 1050 Table 'sunittest_smw_object_ids' already exists ()

Backtrace:
#0 /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/database/Database.php(975): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#1 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/MySQLTableBuilder.php(76): Wikimedia\Rdbms\Database->query(string, string)
#2 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/TableBuilder.php(142): SMW\SQLStore\TableBuilder\MySQLTableBuilder->doCreateTable(string, array)
#3 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(112): SMW\SQLStore\TableBuilder\TableBuilder->create(SMW\SQLStore\TableBuilder\Table)
#4 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(376): SMW\SQLStore\Installer->install(boolean)
#5 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/MwDatabaseTableBuilder.php(207): SMWSQLStore3->setup(boolean)
#6 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/MwDatabaseTableBuilder.php(121): SMW\Tests\Utils\MwDatabaseTableBuilder->setupDatabaseTables()
#7 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/MwDBaseUnitTestCase.php(126): SMW\Tests\Utils\MwDatabaseTableBuilder->doBuild()
#8 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): SMW\Tests\MwDBaseUnitTestCase->run(PHPUnit_Framework_TestResult)
#9 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult)
#10 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult)
#11 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(440): PHPUnit_Framework_TestSuite->run(PHPUnit_Framework_TestResult)
#12 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/src/TextUI/Command.php(149): PHPUnit_TextUI_TestRunner->doRun(PHPUnit_Framework_TestSuite, array)
#13 /home/travis/build/SemanticMediaWiki/mw/vendor/phpunit/phpunit/src/TextUI/Command.php(100): PHPUnit_TextUI_Command->run(array, boolean)
#14 /home/travis/build/SemanticMediaWiki/mw/tests/phpunit/phpunit.php(133): PHPUnit_TextUI_Command::main()
#15 /home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php(111): PHPUnitMaintClass->execute()
#16 /home/travis/build/SemanticMediaWiki/mw/tests/phpunit/phpunit.php(163): require(string)
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

**Comment by mwjames** [comment]
I set "master" on "Allowed Failures" as I currently don't have the means (i.e. time) to deal with this given that REL1_26 and REL1_28 just working fine. Maybe some present from the eloquent WMF developer community for making volunteer developers to work on weekends, who knows!

**Comment by s7eph4n** [comment]
This seems to not occur anymore in #30. See [the travis run](https://travis-ci.org/SemanticMediaWiki/SemanticGlossary/builds/247684545?utm_source=github_status&utm_medium=notification).

I don't know if this was an issue in MW that was actually fixed in the meantime or if it's more complicated and the test passing now does not mean anything. So I propose to keep this issue open for the time being and monitor the situation.

**Comment by mwjames** [comment]
> I don't know if this was an issue in MW that was actually fixed in the
> meantime or if it's more complicated and the test passing now does not mean

[0] happened and it got silently fixed in [1].

[0] https://phabricator.wikimedia.org/T168207#3378916
[1] https://gerrit.wikimedia.org/r/#/c/361717/2

We can assume this to be fixed til the next time.
