### ISSUE TITLE
[MW 1.31] Call to undefined function SG\wfProfileIn()

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticGlossary#41]
### Setup and configuration

- MW version: 1.31
- PHP version: 7.2.5-0ubuntu0.18.04.1
- DB (MySQL etc.): 5.7.22-0ubuntu18.04.1
- SMW version: 2.5.6
- SG version: 2.2.0
- Lingo version: 2.0.3

### Issue

Produces a [stack trace] and outputs:

```
[26ede58529768eca57968c9f] /wiki01/index.php/Main_Page Error from line 58 of /var/www/wikis/wiki01/extensions/SemanticGlossary/src/LingoBackendAdapter.php: Call to undefined function SG\wfProfileIn()

Backtrace:

#0 /var/www/wikis/wiki01/extensions/Lingo/src/LingoParser.php(191): SG\LingoBackendAdapter->next()
#1 /var/www/wikis/wiki01/extensions/Lingo/src/LingoParser.php(163): Lingo\LingoParser->buildLingo()
#2 /var/www/wikis/wiki01/extensions/Lingo/src/LingoParser.php(223): Lingo\LingoParser->getLingoTree()
#3 /var/www/wikis/wiki01/extensions/Lingo/src/LingoParser.php(80): Lingo\LingoParser->realParse(Parser, string)
#4 /var/www/wikis/wiki01/includes/Hooks.php(177): Lingo\LingoParser->parse(Parser, string, StripState)
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

Happens when opening any page in the wiki.

**Comment by s7eph4n** [comment]
It should be safe to just delete any calls to wfProfileIn.

**Comment by s7eph4n** [comment]
Fixed in 2fad044e20ce7fc

Guess I should make a release.

**Comment by gesinn-it** [comment]
...cool! Should the new release also require Lingo 3.x?

**Comment by s7eph4n** [comment]
For the moment I don't see the need. You can use Lingo 3.0, but 2.x should also still work and might be preferred by some.

**Comment by hermannschwaerzlerUIBK** [comment]
This issue can be closed, can't it?
The relevant fix is part of master and all releases since quite some time...
