### ISSUE TITLE
MW 1.34+ fails with "LingoParser.php: Call to undefined function MediaWiki\suppressWarnings()"

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticGlossary#53]
### Setup and configuration

- MW version: 1.34+
- SMW version: 3.1+
- SG version: master
- Lingo version: mediawiki/lingo (dev-master 8e12306): Cloning 8e1230678f from cache

### Issue

https://travis-ci.org/SemanticMediaWiki/SemanticGlossary/jobs/564366791

```
[e4b597705969349af14db18e] [no req]   Error from line 223 of /home/travis/build/SemanticMediaWiki/mw/extensions/Lingo/src/LingoParser.php: Call to undefined function MediaWiki\suppressWarnings()
```

### Stack trace
```
Importing from smw.vocab.json ...
   ... creating MediaWiki:Smw import skos ...
[e4b597705969349af14db18e] [no req]   Error from line 223 of /home/travis/build/SemanticMediaWiki/mw/extensions/Lingo/src/LingoParser.php: Call to undefined function MediaWiki\suppressWarnings()
Backtrace:
#0 /home/travis/build/SemanticMediaWiki/mw/extensions/Lingo/src/LingoParser.php(82): Lingo\LingoParser->realParse(Parser)
#1 /home/travis/build/SemanticMediaWiki/mw/extensions/Lingo/src/Lingo.php(53): Lingo\LingoParser->parse(Parser)
#2 /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php(174): Lingo\Lingo::Lingo\{closure}(WikitextContent, Title, ParserOutput)
#3 /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#4 /home/travis/build/SemanticMediaWiki/mw/includes/content/AbstractContent.php(559): Hooks::run(string, array)
#5 /home/travis/build/SemanticMediaWiki/mw/includes/Revision/RenderedRevision.php(265): AbstractContent->getParserOutput(Title, NULL, ParserOptions, boolean)
#6 /home/travis/build/SemanticMediaWiki/mw/includes/Revision/RenderedRevision.php(234): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#7 /home/travis/build/SemanticMediaWiki/mw/includes/Revision/RevisionRenderer.php(222): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string)
#8 /home/travis/build/SemanticMediaWiki/mw/includes/Revision/RevisionRenderer.php(151): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#9 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#10 /home/travis/build/SemanticMediaWiki/mw/includes/Revision/RenderedRevision.php(197): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#11 /home/travis/build/SemanticMediaWiki/mw/includes/Storage/DerivedPageDataUpdater.php(1289): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#12 /home/travis/build/SemanticMediaWiki/mw/includes/Storage/PageUpdater.php(725): MediaWiki\Storage\DerivedPageDataUpdater->getCanonicalParserOutput()
#13 /home/travis/build/SemanticMediaWiki/mw/includes/page/WikiPage.php(1920): MediaWiki\Storage\PageUpdater->saveRevision(CommentStoreComment, integer)
#14 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(124): WikiPage->doEditContent(WikitextContent, CommentStoreComment, integer)
#15 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(110): SMW\Importer\ContentCreators\TextContentCreator->doCreateContent(WikiPage, Title, SMW\Importer\ImportContents)
#16 [internal function]: SMW\Importer\ContentCreators\TextContentCreator->SMW\Importer\ContentCreators\{closure}(integer, Wikimedia\Rdbms\DatabaseMysqli)
#17 /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/database/Database.php(3615): call_user_func(Closure, integer, Wikimedia\Rdbms\DatabaseMysqli)
#18 /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/database/Database.php(3415): Wikimedia\Rdbms\Database->runOnTransactionIdleCallbacks(integer)
#19 /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->onTransactionCommitOrIdle(Closure)
#20 /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/database/DBConnRef.php(589): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#21 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(836): Wikimedia\Rdbms\DBConnRef->onTransactionCommitOrIdle(Closure)
#22 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(111): SMW\MediaWiki\Connection\Database->onTransactionIdle(Closure)
#23 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Importer/ContentCreators/DispatchingContentCreator.php(75): SMW\Importer\ContentCreators\TextContentCreator->create(SMW\Importer\ImportContents)
#24 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Importer/Importer.php(133): SMW\Importer\ContentCreators\DispatchingContentCreator->create(SMW\Importer\ImportContents)
#25 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Importer/Importer.php(109): SMW\Importer\Importer->doImportContents(SMW\Importer\ImportContents)
#26 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1294): SMW\Importer\Importer->doImport()
#27 /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php(174): SMW\MediaWiki\Hooks->onAfterCreateTablesComplete(SMW\SQLStore\TableBuilder\MySQLTableBuilder, Onoi\MessageReporter\ObservableMessageReporter, SMW\Options)
#28 /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#29 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(191): Hooks::run(string, array)
#30 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(398): SMW\SQLStore\Installer->install(SMW\Options)
#31 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Store.php(506): SMWSQLStore3->setup(SMW\Options)
#32 /home/travis/build/SemanticMediaWiki/mw/includes/installer/DatabaseUpdater.php(489): SMW\Store::setupStore(boolean, SMW\Options)
#33 /home/travis/build/SemanticMediaWiki/mw/includes/installer/DatabaseUpdater.php(457): DatabaseUpdater->runUpdates(array, boolean)
#34 /home/travis/build/SemanticMediaWiki/mw/maintenance/update.php(209): DatabaseUpdater->doUpdates(array)
#35 /home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php(99): UpdateMediaWiki->execute()
#36 /home/travis/build/SemanticMediaWiki/mw/maintenance/update.php(281): require_once(string)
#37 {main}
```

**Comment by krabina** [comment]
Since this is related to a old and obsolete MW version, I am closing this. We have an improved testing environment for current releases. Should this come up anywhere, there should be a new ticket.
