### ISSUE TITLE
Class 'SMW\ApplicationFactory' not found on SMW 4.0.0

### ISSUE THREAD

**Issue by WouterRademaker** [SemanticMediaWiki/SemanticGlossary#67]
### Setup and configuration

- MW version:1.36.2
- PHP: 7.4.3 (fpm-fcgi)
- MariaDB: 10.3.32-MariaDB-0ubuntu0.20.04.1
- ICU: 66.1
- SMW version: 4.0.0
- SG version: dev-master ([37f70b3e0b8b4a2f34c575b81b66f93cc4fd5699](https://github.com/SemanticMediaWiki/SemanticGlossary/commit/37f70b3e0b8b4a2f34c575b81b66f93cc4fd5699))
- Lingo version: 3.1.1

### Issue

Error: Class 'SMW\ApplicationFactory' not found

Backtrace:

from extensions/SemanticMediaWiki/src/InMemoryPoolCache.php(65)
#0 extensions/SemanticMediaWiki/src/Services/SharedServicesContainer.php(334): SMW\InMemoryPoolCache::getInstance()
#1 [internal function]: SMW\Services\SharedServicesContainer->SMW\Services\{closure}()
#2 vendor/onoi/callback-container/src/CallbackContainerBuilder.php(260): call_user_func_array()
#3 vendor/onoi/callback-container/src/CallbackContainerBuilder.php(288): Onoi\CallbackContainer\CallbackContainerBuilder->getReturnValueFromCallbackHandlerFor()
#4 vendor/onoi/callback-container/src/CallbackContainerBuilder.php(195): Onoi\CallbackContainer\CallbackContainerBuilder->getReturnValueFromSingletonFor()
#5 extensions/SemanticMediaWiki/src/Services/ServicesFactory.php(528): Onoi\CallbackContainer\CallbackContainerBuilder->singleton()
#6 extensions/SemanticMediaWiki/src/SQLStore/SQLStoreFactory.php(615): SMW\Services\ServicesFactory->getInMemoryPoolCache()
#7 extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityIdManager.php(1063): SMW\SQLStore\SQLStoreFactory->newIdCacheManager()
#8 extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityIdManager.php(158): SMW\SQLStore\EntityStore\EntityIdManager->initCache()
#9 extensions/SemanticMediaWiki/src/SQLStore/SQLStoreFactory.php(143): SMW\SQLStore\EntityStore\EntityIdManager->__construct()
#10 extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(173): SMW\SQLStore\SQLStoreFactory->newEntityIdManager()
#11 extensions/SemanticMediaWiki/src/StoreFactory.php(61): SMW\SQLStore\SQLStore->__construct()
#12 extensions/SemanticMediaWiki/src/StoreFactory.php(42): SMW\StoreFactory::newFromClass()
#13 extensions/SemanticGlossary/src/LingoBackendAdapter.php(42): SMW\StoreFactory::getStore()
#14 extensions/Lingo/src/Lingo.php(48): SG\LingoBackendAdapter->__construct()
#15 extensions/includes/Setup.php(838): Lingo\Lingo::Lingo\{closure}()
#16 extensions/includes/WebStart.php(87): require_once(string)
#17 extensions/index.php(44): require(string)
#18 {main}

**Comment by WouterRademaker** [comment]
Sorry my mistake, hadn't fully enabled SMW
